use_frameworks!

target 'ZebraKing_Example' do
  pod 'ZebraKing', :path => '../'
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'Kingfisher', '~> 4.9.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
