source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.bmkp.cn:rdc_ios/PodsRepo.git'

use_frameworks!
platform :ios, '8.2'
target 'BMKP_Chat_Example' do
  pod 'BMKP_Chat', :path => '../'


end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
